In [98]:
import numpy  as np
import matplotlib.pyplot as plt
import pandas as pd


In [99]:
dataset = pd.read_csv('C:/Users/Santhosh/Downloads/DAP data set1/Education_updated.csv')






In [100]:
dataset.isna().sum().sum()


0

In [101]:
dataset['Percent of adults with less than a high school diploma, 1970'].isna().sum()

0

In [102]:

dataset['Percent of adults completing some college (1-3 years), 1970'].isna().sum()
dataset['Percent of adults completing four years of college or higher, 1970'].isna().sum()
dataset['Percent of adults with less than a high school diploma, 1980'].isna().sum()
dataset['Percent of adults with a high school diploma only, 1970'].isna().sum()
dataset['Percent of adults with a high school diploma only, 1970'].isna().sum()


0

In [103]:
dataset['Percent of adults completing four years of college or higher, 1970'].isna().sum()

0

In [86]:
X=dataset.iloc[:,3:23].values
print(X)

[[47.7 31.1 10.6 ... 27.  28.9 32.1]
 [58.7 25.9  7.5 ... 30.8 29.9 25.5]
 [54.8 31.1  7.7 ... 33.6 28.4 26.6]
 ...
 [ nan  nan  nan ... 38.4 19.7 19.9]
 [ nan  nan  nan ... 25.7 27.2 18. ]
 [ nan  nan  nan ... 33.3 15.5 24.6]]


In [87]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)

X=imputer.transform(X)

In [32]:
print(X)

[[5.05712512e+00 5.37162372e+00 4.93697609e+00 5.18782987e+00
  5.23733120e+07]
 [5.05712512e+00 5.37162372e+00 4.93697609e+00 5.18782987e+00
  1.06230600e+06]
 [2.00000000e+00 2.00000000e+00 2.00000000e+00 2.00000000e+00
  6.61100000e+03]
 ...
 [2.00000000e+00 2.00000000e+00 2.00000000e+00 2.00000000e+00
  4.93157363e+04]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  4.93157363e+04]
 [3.00000000e+00 2.00000000e+00 2.00000000e+00 2.00000000e+00
  4.93157363e+04]]
